routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('clean-data',function (){
    ini_set('max_execution_time', '0');

    dd('ok');
/*
    $comps = \App\Models\PropertyValuationComparable::take(10000)->whereNull('area_new')->whereNotNull('area')->get();

    foreach ($comps as $comp){
        try{
            $comp->area_new = (float) $comp->area;
            $comp->area = null;
            $comp->save();
        }catch (Exception $e){

        }
    }

    dd($comps->count());*/

});
Route::get('properties/{property}/report', 'PropertyController@getReport');
Route::get('properties/report/footer.html', function(){
    $query = request()->all();
    return view('valuations-reports.layout.footer',compact('query'));
})->name('report.footer');

Route::get('valuations/{assignment}/properties/{property}/print-preview', 'ValuationReportController@preview');



Route::prefix('/api/app')->group(function () {
    Route::get('assignments', 'BSAppController@getAssignments');
    Route::get('assignments/{assignment}/properties', 'BSAppController@getProperties');
    Route::post('assignments/{assignment}/properties/create', 'BSAppController@saveProperty');
    Route::get('properties/{property}/defects', 'BSAppController@getDefects');
    Route::post('properties/{property}/defects/create', 'BSAppController@saveDefects');

});

Route::post('/api/auth/user',function (){
    return auth()->user();
});

Route::group(['middleware' => 'web'], function () {
    Route::get('/{any}', 'LaravueController@index')->where('any', '.*');
});

app/Models/Media.php
<?php

namespace App\Models;

use App\Laravue\Models\User;
use Illuminate\Database\Eloquent\Model;
use Spatie\MediaLibrary\Models\Media as BaseMedia;

class Media extends BaseMedia
{
    protected $appends = ['full_url','title'];

    public function downloader()
    {
        $this->hasMany(User::class);
    }

    public function getFullUrlAttribute()
    {
        return $this->getFullUrl();
    }

    public function getPathAttribute()
    {
        return $this->getPath();
    }

    public function getTitleAttribute()
    {
        return $this->hasCustomProperty('title') ? $this->getCustomProperty('title') : '';
    }

    public function setTitleAttribute($value)
    {
        return $this->setCustomProperty('title',$value);
    }
}

resources/views/valuations-reports/pages/appendices.blade.php
@foreach($property->appendices as $appendix)
    <page size="A4" id="content-pages">
        <div class="section-wrapper">

            <div class="contents">
                <h1 class="main-heading">{{ $appendix->title }}</h1>

                <table class="table-1 image-table" cellspacing="0">
                    <tbody>

                    <tr>
                        <td><img class="img-fluid" src="{{ $appendix->path }}" style="height:100%;max-height:1150px; width:100%; min-width:100%;max-width:100%;"></td>
                    </tr>

                    </tbody>
                </table>
            </div>
        </div>

    </page>
@endforeach

resources/views/valuations-reports/pages/details-2.blade.php
<page size="A4" id="content-pages">
    <div class="section-wrapper">


        <div class="contents">
            <h1 class="main-heading">{{ $property->assignment->title }}</h1>

            <table class="table-1" cellspacing="0">
                <tbody>
                <tr><th colspan="10">SURROUNDINGS</th></tr>


                @php
                    $surroundings_chunk = collect($property->surroundings)->chunk(3);
                @endphp

                @foreach($surroundings_chunk as $surroundings)
                    <tr>
                        @foreach($surroundings as $surrounding)
                            <td class="checkbox-width b-0">
                                <span class="checked-box" style="display: inline-block;"></span>
                                <span class="check-label b-0">{{ $surrounding }}</span>
                            </td>
                        @endforeach
                    </tr>
                @endforeach

                </tbody>
            </table>


            <table class="table-1" cellspacing="0">
                <tbody>
                <tr><th>MARKET COMMENTARY</th></tr>
                <tr>
                    <td>
                        {!! $property->market_commentary !!}
                    </td>
                </tr>
                </tbody>
            </table>


            <table class="table-1" cellspacing="0">
                <tbody>
                <tr><th>ASSUMPTIONS</th></tr>
                <tr>
                    <td>
                        <p>
                            {{ $property->assumptions }}
                        </p>
                        <p>
                            {{ $property->special_assumptions }}
                        </p>
                    </td>
                </tr>
                </tbody>
            </table>

            @if(count($property->rentels))
                <table class="table-1" cellspacing="0">
                    <tbody>
                    <tr><th>Comparables for Market Rent</th></tr>
                    <tr>
                        <td class="p-0">
                            <table class="table-blue-head" cellspacing="0">
                                <tbody>
                                <tr>
                                    <th>Date</th>
                                    <th>Type</th>
                                    <th>Transaction Type</th>
                                    <th>Size(SqFt)</th>
                                    <th>Rate/(SqFt)</th>
                                    <th>Market Rent(AED)</th>
                                    <th>Type of Unit</th>
                                    <th>Additional Details</th>
                                </tr>

                                @foreach($property->rentels as $rentel)
                                    <tr>
                                        <td>{{ $rentel->date->toDateString() }}</td>
                                        <td>{{ $rentel->type }}</td>
                                        <td>{{ $rentel->transaction_type }}</td>
                                        <td>{{ $rentel->size }}</td>
                                        <td>CALCUATED</td>
                                        <td>{{ $rentel->market_rent }}</td>
                                        <td>{{ $rentel->unit_type }}</td>
                                        <td>{{ $rentel->details }}</td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>



                        </td>
                    </tr>
                    </tbody>
                </table>
            @endif

        </div>


    </div>

</page>

resources/views/valuations-reports/pages/details-3.blade.php
<page size="A4" id="content-pages">
    <div class="section-wrapper">


        <div class="contents">
            <h1 class="main-heading">RESIDENTIAL VALUATION REPORT</h1>

            <table class="table-1" cellspacing="0">
                <tbody>
                <tr><th colspan="10">SURROUNDINGS</th></tr>


                @php
                    $surroundings_chunk = collect($property->surroundings)->chunk(3);
                @endphp

                @foreach($surroundings_chunk as $surroundings)
                    <tr>
                        @foreach($surroundings as $surrounding)
                            <td class="checkbox-width b-0">
                                <span class="checked-box" style="display: inline-block;"></span>
                                <span class="check-label b-0">{{ $surrounding }}</span>
                            </td>
                        @endforeach
                    </tr>
                @endforeach

                </tbody>
            </table>


            <table class="table-1" cellspacing="0">
                <tbody>
                <tr><th>MARKET COMMENTARY</th></tr>
                <tr>
                    <td>
                        {!! $property->market_commentary !!}
                    </td>
                </tr>
                </tbody>
            </table>


            <table class="table-1" cellspacing="0">
                <tbody>
                <tr><th>ASSUMPTIONS</th></tr>
                <tr>
                    <td>
                        <p>
                            {{ $property->assumptions }}
                        </p>
                        <p>
                            {{ $property->special_assumptions }}
                        </p>
                    </td>
                </tr>
                </tbody>
            </table>

            @if(count($property->rentels))
                <table class="table-1" cellspacing="0">
                    <tbody>
                    <tr><th>Comparables for Market Rent</th></tr>
                    <tr>
                        <td class="p-0">
                            <table class="table-blue-head" cellspacing="0">
                                <tbody>
                                <tr>
                                    <th>Date</th>
                                    <th>Type</th>
                                    <th>Transaction Type</th>
                                    <th>Size(SqFt)</th>
                                    <th>Rate/(SqFt)</th>
                                    <th>Market Rent(AED)</th>
                                    <th>Type of Unit</th>
                                    <th>Additional Details</th>
                                </tr>

                                @foreach($property->rentels as $rentel)
                                    <tr>
                                        <td>{{ $rentel->date->toDateString() }}</td>
                                        <td>{{ $rentel->type }}</td>
                                        <td>{{ $rentel->transaction_type }}</td>
                                        <td>{{ $rentel->size }}</td>
                                        <td>CALCUATED</td>
                                        <td>{{ $rentel->market_rent }}</td>
                                        <td>{{ $rentel->unit_type }}</td>
                                        <td>{{ $rentel->details }}</td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>



                        </td>
                    </tr>
                    </tbody>
                </table>
            @endif

        </div>


    </div>

</page>

resources/views/valuations-reports/pages/end-details.blade.php
<page size="A4" id="content-pages">
    <div class="section-wrapper">



        <div class="contents">
            <h1 class="main-heading">{{ $property->assignment->title }}</h1>

            <table class="table-1" cellspacing="0">
                <tbody>
                <tr><th>Definition of
                        @foreach($property->basis as $b)
                            {{ $b }}{{ ($loop->last)? '':',' }}
                        @endforeach
                        : RICS & IVSC</th></tr>
                @include('valuations-reports._partials.valuation_basis')
                </tbody>
            </table>

            <table class="table-1" cellspacing="0">
                <tbody>
                <tr><th>Valuation Methodology</th></tr>
                @if(in_array('Comparison Method',$property->methods))
                    <tr>
                        <td>The Sales Comparison Method is a process involving analysing sales and asking prices of similar units and comparing these to the subject property. Comparative analysis isolates similarities and differences in the property rights appraised, market conditions, size, location and physical features.</td>
                    </tr>
                @endif
                @if(in_array('Cost Method',$property->methods) or in_array('Cost Method (Under Construction)',$property->methods))
                    <tr>
                        <td>Depreciated Replacement Cost (DRC) is based on an estimate of the Market Value for the current use of the land in addition to the current gross replacement costs of improvements less allowances for physical deterioration and all relevant forms of obsolescence and optimization.</td>
                    </tr>
                @endif
                @if(in_array('Income Method',$property->methods))
                    <tr>
                        <td>The Income Capitalization Method is a process involving analysing the potential rental income and deducted expenses to work out the net rental income. This income is then capitalized at a rate to work out the Market Value of the property.</td>
                    </tr>
                @endif
                </tbody>
            </table>

            <table class="table-1" cellspacing="0">
                <tbody>
                <tr><th>Valuation Assumptions and Caveat</th></tr>
                <tr>
                    <td><strong>General</strong><br><br>
                        We assume no responsibility for economic or physical factors which may affect the opinions in this report which occur after the valuation date.<br><br>

                        We have relied extensively on information provided during discussions and in hardcopy by The Client. Whilst we believe that the data collected is accurate
                        and reliable, Land Sterling has not, as part of the valuation, performed an independent audit or review of the information gathered and does not express an
                        opinion or any other form of assurance on the accuracy of such information. No responsibility is assumed for errors or omissions, or for information not
                        disclosed which might otherwise affect the valuation estimate.<br><br>

                        No opinion is intended to be expressed for matters which require legal expertise or specialised investigation or knowledge beyond that customarily
                        employed by property valuers. We were acting as independent and external Valuers.
                        Unless otherwise noted, no consideration has been given in this valuation to the value of the property located on the premises which is considered to be
                        personal property, only the real immovable property has been considered.<br><br>

                        Maps and exhibits included in this report are for illustration only as an aid in visualizing matters discussed within the report. They should not be considered
                        as surveys or relied upon for any other purpose, nor should they be removed from, reproduced or used apart from the report.<br><br>

                        This valuation has been prepared in accordance with the Valuation Standards of the Royal Institution of Chartered Surveyors (RICS), UAE Law and
                        Regulations, and also in conformity with the International Valuation Standards(IVS).<br><br>

                        Our valuation report is only for the use of our client and no responsibility is accepted to any third party for the whole or any part of its contents. Neither the whole nor any part of this valuation nor any reference there may be included in any published document, circular or statement nor published in any way without our prior written approval of the form or context in which it may appear<br><br>

                        <strong>Compliance of property</strong><br><br>
                        The property is valued assuming that it is in full compliance with all applicable state and local environmental regulations and laws.<br><br>
                        The property is valued assuming that all applicable zoning and use regulations and restrictions have been and will be complied with, unless otherwise stated.<br><br>

                        <strong>Condition of Land</strong><br><br>
                        Our enquiries have not revealed any contamination affecting the property or neighbouring properties which would affect our valuation.<br><br>
                        However, should it be established subsequently that contamination, seepage or pollution exists at the properties or on any neighbouring land or that the premises have been or are being put to a contaminative use this might reduce the values now reported.<br><br>

                        <strong>Suitability for Debt Financing or Mortgage Security</strong><br><br>
                        On the basis of the information provided and subject to the assumptions and limiting conditions outlined in this report, we are of the opinion that the property is suitable security for first mortgage finance purposes. This is based on the assumption that the lender complies with its own lending guidelines as well as prudent finance industry lending practices.<br><br>

                        The lender will consider all prudent aspects of credit risk for any potential borrower, including the borrower’s ability to service and repay any mortgage loan. Further, the valuation is prepared on the assumption that the lender is providing mortgage financing at a conservative and prudent loan to value ratio.
                        <br><br>
                        We anticipate a Marketing Period of '{{ $property->marketing_period }}' to achieve a sale of the property subject to an appropriate marketing strategy.<br><br>
                    </td>
                </tr>
                </tbody>
            </table>

        </div>


    </div>

</page>

resources/views/valuations-reports/pages/fadb-summary.blade.php
<page size="A4" id="content-pages">
    <div class="section-wrapper">

        <div class="contents">
            <h1 class="main-heading">{{ $property->assignment->title }}</h1>

            <table class="table-1" cellspacing="0">
                <tbody>
                <tr><th colspan="2">SUMMARY PAGE</th></tr>

                <tr>
                    <td class="grey-bg">Valuation Company</td>
                    <td>Land Sterling Property Consultants</td>
                </tr>
                <tr>
                    <td class="grey-bg">Date of inspection</td>
                    <td>{{ optional($property->inspection_datetime)->toFormattedDateString() }}</td>
                </tr>
                <tr>
                    <td class="grey-bg">Reference Number</td>
                    <td>{{ $property->ref_number }}</td>
                </tr>

                <tr>
                    <td class="grey-bg">Applicant's Name</td>
                    <td>{{ $property->applicant_name }}</td>
                </tr>
                <tr>
                    <td class="grey-bg">Owner Name</td>
                    <td>{{ $property->current_owner }}</td>
                </tr>
                <tr>
                    <td class="grey-bg">Property Address (New)</td>
                    <td>{{ $property->address_new }}</td>
                </tr>
                <tr>
                    <td class="grey-bg">Property Address (Old)</td>
                    <td>{{ $property->address_old }}</td>
                </tr>
                <tr>
                    <td class="grey-bg">Developer</td>
                    <td>{{ $property->developer }}</td>
                </tr>
                <tr>
                    <td class="grey-bg">Project</td>
                    <td>Sulafa Tower</td>
                </tr>
                <tr>
                    <td class="grey-bg">Community</td>
                    <td>{{  $property->community->name }}</td>
                </tr>
                <tr>
                    <td class="grey-bg">Occupancy Status</td>
                    <td>{{ $property->occupancy }}</td>
                </tr>
                <tr>
                    <td class="grey-bg">Market Value (AED) </td>
                    <td>CALCUATED</td>
                </tr>
                <tr>
                    <td class="grey-bg">Estimated rental income (AED)</td>
                    <td>CALCUATED</td>
                </tr>
                <tr>
                    <td class="grey-bg">Plot Area</td>
                    <td> {{ $property->area }} {{ $property->area_unit }}</td>
                </tr>
                <tr>
                    <td class="grey-bg">Built –up Area</td>
                    <td>{{ $property->bua }} {{ $property->bua_unit }}</td>
                </tr>
                <tr>
                    <td class="grey-bg">Property Type</td>
                    <td>Apartment</td>
                </tr>
                <tr>
                    <td class="grey-bg">Inspection Type</td>
                    <td>{{ $property->type->title }}</td>
                </tr>
                <tr>
                    <td class="grey-bg">Valuation Approach/Methodology</td>
                    <td>{{ $property->primary_market_value }}</td>
                </tr>
                <tr>
                    <td class="grey-bg">Age of Building</td>
                    <td>{{ $property->age_years }}</td>
                </tr>
                <tr>
                    <td class="grey-bg">Estimated Remaining Economic life</td>
                    <td>{{ $property->life_years - $property->age_years }}</td>
                </tr>
                <tr>
                    <td class="grey-bg"> Interest to be valued/Tenure</td>
                    <td>{{ $property->interests_text }}</td>
                </tr>
                <tr>
                    <td class="grey-bg">Completion Status</td>
                    <td>{{ $property->property_status }}</td>
                </tr>
                <tr>
                    <td class="grey-bg">Total Construction Cost</td>
                    <td>{{ $property->total_construction_cost }}</td>
                </tr>
                <tr>
                    <td class="grey-bg">Existing market value at the current millstone ( as is )</td>
                    <td>{{ $property->existing_market_value }}</td>
                </tr>
                <tr>
                    <td class="grey-bg">Estimated market value upon Completion</td>
                    <td>{{ $property->estimated_market_value }}</td>
                </tr>
                <tr>
                    <td class="grey-bg">Other remarks highlighted by valuer</td>
                    <td>{{ $property->other_remarks }}</td>
                </tr>
                <tr>
                    <td class="grey-bg">Key Defects in Property</td>
                    <td>{{ $property->other_10 }}</td>
                </tr>
                <tr>
                    <td class="grey-bg">As per Approved Municipality Plans</td>
                    <td>{{ ($property->approved_municipality_plans)? 'Yes':'No' }}</td>
                </tr>
                <tr>
                    <td class="grey-bg">Property Condition</td>
                    <td>{{ $property->property_condition }}</td>
                </tr>
                <tr>
                    <td class="grey-bg">Passing Rent</td>
                    <td>{{ $property->passing_rent }}</td>
                </tr>
                <tr>
                    <td class="grey-bg">Number of units</td>
                    <td>{{ $property->no_of_units }}</td>
                </tr>
                <tr>
                    <td class="grey-bg">Is the valuation done in accordance with RICS standards</td>
                    <td>Yes</td>
                </tr>
                </tbody>

            </table>
        </div>

    </div>
</page>

resources/views/valuations-reports/pages/methods.blade.php
{{--
@if(count($property->methods) <= 2)

@else
    <page size="A4" id="content-pages">
        <div class="section-wrapper">


            <div class="contents">
                <h1 class="main-heading">{{ $property->assignment->title }}</h1>

                @includeWhen(in_array('Comparison Method',$property->methods ?? []),'valuations-reports.methods.comparison',['prop'=>$property])

                @includeWhen(in_array('Cost Method',$property->methods ?? []),'valuations-reports.methods.cost',['prop'=>$property])

            </div>


        </div>

    </page>
@endif--}}

<page size="A4" id="content-pages">
    <div class="section-wrapper">


        <div class="contents">
            <h1 class="main-heading">{{ $property->assignment->title }}</h1>



            @includeWhen(in_array('Comparison Method',$property->methods ?? []),'valuations-reports.methods.comparison',['prop'=>$property])

            @includeWhen(in_array('Cost Method',$property->methods ?? []),'valuations-reports.methods.cost',['prop'=>$property])

            @includeWhen(in_array('Cost Method (Under Construction)',$property->methods ?? []),'valuations-reports.methods.cost-uc',['prop'=>$property])

            @includeWhen(in_array('Income Method',$property->methods ?? []),'valuations-reports.methods.income',['prop'=>$property])

            <table class="table-1" cellspacing="0">
                <tbody>
                <tr><th>VALUATION RATIONALE</th></tr>
                <tr>
                    <td>
                        {{ $property->valuation_rationale_1 }}

                        <br><br>
                        {{ $property->valuation_rationale_2 }}

                    </td>
                </tr>
                </tbody>
            </table>

            <table class="table-1" cellspacing="0">
                <tbody>
                <tr><th>SURVEYOR DECLARATION</th></tr>
                <tr>
                    <td>Land Sterling confirms that the appointed Valuer has the necessary market knowledge, skills, and understanding to undertake this valuation competently and to provide an objective and unbiased valuation</td>
                </tr>
                </tbody>
            </table>
        </div>


    </div>

</page>

resources/views/valuations-reports/pages/photos.blade.php
@php
    $photos_chunk = $property->photos->take($property->include_photos_count)->chunk(8)
@endphp

@foreach($photos_chunk as $photos)
    <!-- Page 6 -->
    <page size="A4" id="content-pages">
        <div class="section-wrapper">

            <div class="contents">
                <h1 class="main-heading">{{ $property->photos_page_title }}</h1>
                <div>
                    @foreach($photos as $photo)
                        {{--{{ dd($photo) }}--}}

                        <div style="width:48%;float:left;padding-left: 1%">
                            <h3 class="img-title">{{ $photo->title }}</h3>
                            @if($property->water_marked_images)
                                <img class="img-fluid" src="{{ $photo->getPath('watermark') }}" style="max-height:280px;min-height:280px; object-position: center; object-fit: cover;">
                            @else
                                <img class="img-fluid" src="{{ $photo->path }}" style="max-height:280px;min-height:280px; object-position: center; object-fit: cover;">
                            @endif
                            {{--</td>--}}
                        </div>

                    @endforeach
                </div>
            </div>
        </div>

    </page>
    <!-- Page 6 end -->
@endforeach